name: Node App Deployment

on:
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_ID }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd /home/ubuntu
            git pull origin
            sudo npm install
